version: "3.7"

services: 

    MySQL:
        image: tuhin2929/sqlrepo
        container_name: db_mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root-pass 
          MYSQL_DATABASE: AFS
          MYSQL_USERNAME: afs
          MYSQL_PASSWORD: Afs2019
        ports:
          - 3336:3306
        networks: 
          nw_riskp:
              ipv4_address: 172.20.0.5 
     
    mongo1:
        image: tuhin2929/mongorepo
        container_name: mongo
        restart: always
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: afs
          MONGO_INITDB_ROOT_PASSWORD: Afs2019
        networks: 
          nw_riskp:
            ipv4_address: 172.20.0.6

    mongo-express:
        image: mongo-express
        container_name: db_mongoEx1
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_SERVER: mongo1
          ME_CONFIG_MONGODB_AUTH_DATABASE: admin
          ME_CONFIG_MONGODB_AUTH_USERNAME: afs
          ME_CONFIG_MONGODB_AUTH_PASSWORD: Afs2019
          ME_CONFIG_MONGODB_PORT: 27017
        depends_on:  
          - mongo1
        links: 
          - mongo1
        networks: 
          nw_riskp:
            ipv4_address: 172.20.0.7
          
    riskProbeAPI:
        image: tuhin2929/apirepo
        container_name: api_rp
        ports: 
          - 3005:3005
        networks: 
          nw_riskp:
            ipv4_address: 172.20.0.8
        depends_on:
         - MySQL
         - mongo1

networks:
  nw_riskp:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
                  
          
    


        
    



